name       : t4k-common
version    : 0.1.1
release    : 3
source     :
    - https://github.com/tux4kids/t4kcommon/archive/refs/tags/upstream/0.1.1.tar.gz : be4cadbcf2728ed6efb1c71e96c209184a7829b65af3625d9410a29fb2fd775a
license    : GPL-3.0-or-later
component  : multimedia.library
summary    : Common library for code shared by TuxType and TuxMath
description: |
    Common library for code shared by TuxType and TuxMath
builddeps  :
    - pkgconfig(librsvg-2.0)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_Pango)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-libpng.patch
    %patch -p1 < $pkgfiles/0001-Make-wrapped_lines-static-to-fix-compile-errors.patch
    %patch -p1 < $pkgfiles/0001-Use-libxml2-to-get-info-from-svg-files-for-frame-cou.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
