name       : t4k-common
version    : 0.1.1
release    : 1
source     :
    - http://kent.dl.sourceforge.net/project/tuxmath/t4k_common/t4k_common-0.1.1.tar.gz : 42c155816dae2c5dad560faa50edaa1ca84536530283d37859c4b91e82675110
license    : GPL-3.0
component  : multimedia.library
summary    : Common library for code shared by TuxType and TuxMath
description: |
    Common library for code shared by TuxType and TuxMath
builddeps  :
    - pkgconfig(librsvg-2.0)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_Pango)
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-libpng.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
